language: cpp
dist: xenial

compiler:
- gcc
- clang

install:
- sudo apt-get install libboost-all-dev

script:
- mkdir -p build 
- cd build
- cmake ../tests
- make
- ./test_mathext
- ./test_stopwatch

after_failure:
- cmake --version
- gcc --version
- g++ --version
- clang --version
